server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/meli-challenge/config-service
          search-paths: config-data
  application:
    name: config-service
